### ISSUE TITLE
Python 3.11 (currently rc2) support

### ISSUE THREAD

**Issue by S1SYPHOS** [fdintino/pillow-avif-plugin#17]
Hey there,
when building its wheels using Python 3.11 (installed via `pyenv`), I get this:

```
gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/path/to/my/project/.tox/py311/include -I/home/two-brain/.pyenv/versions/3.11.0rc2/include/python3.11 -c src/pillow_avif/_avif.c -o build/temp.linux-x86_64-cpython-311/src/pillow_avif/_avif.o
      src/pillow_avif/_avif.c:4:10: fatal error: avif/avif.h: No such file or directory
          4 | #include "avif/avif.h"
            |          ^~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
```

All other python versions succeed just fine. Thanks so much for this package anyway! :+1:

**Comment by fdintino** [comment]
That would be because the other versions of python have manylinux wheels hosted on PyPI. If you wanted to build it yourself you would need to install the build dependencies for libavif (e.g. on debian or ubuntu, [this script](https://github.com/fdintino/pillow-avif-plugin/blob/master/.github/workflows/linux-install.sh)) and then build and install libavif (see [install_libavif.sh](https://github.com/fdintino/pillow-avif-plugin/blob/master/depends/install_libavif.sh)). But I wouldn't recommend going to the trouble...I'll add python 3.11 to the build matrix and push up the wheels to PyPI.

**Comment by fdintino** [comment]
I've just uploaded python 3.11 wheels to PyPI. Could you try it out and see if it's working now for you?

**Comment by S1SYPHOS** [comment]
@fdintino  .. working as expected now, thank you very much!
