### ISSUE TITLE
How to use svt-av1 on macOS?

### ISSUE THREAD

**Issue by jnoring-pw** [fdintino/pillow-avif-plugin#52]
Any advice on how to use this library on macOS? I can't seem to get it to load no matter what I do. Any advice welcome.

**Comment by fdintino** [comment]
SVT-AV1 is now included in the macos arm64 wheels.

**Comment by jnoring-pw** [comment]
I can confirm it's now present, although I get some strange errors:

```
Svt[error]: Error Instance 1: Source Width must be even for YUV_420 colorspace
Svt[error]: Error Instance 1: Source Height must be even for YUV_420 colorspace
Svt[warn]: If you are using tiles with the intent of increasing the decoder speed, please also consider using --fast-decode 1, especially if the intended decoder is running with limited multi-threading capabilities.
```

...my goal was only to test `svt` and see if the performance was better than libaom. Any guidance on which library I should prefer?

**Comment by fdintino** [comment]
Those errors are due to a limit of SVT-AV1: it will only encode source images whose widths and heights are even numbers.

I typically use rav1e or SVT-AV1, depending on the circumstances. You can pass `speed=` as a keyword argument to the `save` method; `speed=0` is the slowest but gives the best quality / compression whereas `speed=9` is the fastest. I've found rav1e to offer a good trade-off of speed and efficiency with `speed=5` or `speed=6` (which you might want if you are encoding images after user upload). SVT-AV1 will give you very good compression if you run it with a slow speed, but it's only really usable that way if you're doing the encoding offline or asynchronously. AOM has a realtime mode that is very fast and is fine if quality and compression aren't very important, and SVT-AV1 can also perform decently with a high speed setting.

**Comment by jnoring-pw** [comment]
Interesting. I'm surprised SVT-AV1 has that limitation; is it only with YUV 4:2:0 inputs?

Let me code up something a bit more scientific and get back to you. ffmpeg has good VMAF support, so now that I have `svt` running, I can test these three encoders and get a decent understanding of their performance, both in terms of runtime and quality.

I'm encoding massive images (think 100k pixels square) that are broken into tiles, so performance/quality tradeoffs are extremely important to me. One surprising finding was going from `speed=6` to `speed=4` resulted in about a 4x slowdown in encode time for about two VMAF points.

**Comment by fdintino** [comment]
I wrote a small python library for libvmaf bindings. There's no documentation (you'll need to look at the tests to see how to use it) and I haven't recently updated the CI, so the binary wheels don't include arm64 or python 3.11, but in case it's helpful: https://github.com/fdintino/pyvmaf (`pip install pyvmaf==1.0.0a1`)
